### ISSUE TITLE
Machine information for experiments

### ISSUE THREAD

**Issue by ledif** [ledif/dimebox#26]
When generating an experiment, machine information should be dumped so that they can be referenced in the future.

One possibility is a `$epoch/jobs/machine.yml` that contains the following information:
- `hostname`
- `uname -a`
- `$ENV`

**Comment by timmiesmith** [comment]
Capturing $ENV when generating an experiment is likely to be of little use because environment setup on login varies from compute nodes.  Adding a dump of $ENV to the job file that is executed by the launch command (e.g., aprun, srun, etc.) is probably what's required.

**Comment by ledif** [comment]
This is true; we are missing crucial information (MPI buffer sizes, etc.) that does not exist in the `$ENV` of the login node.

I suggest we also capture per-job information by adding something like the following to the beginning of the job files generated:
```bash
$MPIRUN1 /bin/env >> experiments/results/$epoch/.env/$name
```

In this instance, `$MPIRUN1$` is the `mpiexec` command with one rank. The reason we need to capture it on one rank is because we don't want to trash the environment dump by having multiple processors write to the same file. One alternative that could exist is creating a wrapper script that only prints if `OMPI_COMM_WORLD_RANK -eq 1` (or the equivalent in different MPI environments). This would require handling multiple MPI environments.

**Comment by ledif** [comment]
Partial support is now available in 489f65b. It only dumps information of the login node, but it's a start. Next is to implement the compute node machine information gathering.

**Comment by ledif** [comment]
Support is enough for now.
