### ISSUE TITLE
Better support for stateful parsers

### ISSUE THREAD

**Issue by dlatypov** [ledif/dimebox#46]
It would be helpful if there was an interface stateful parsers could use to safely initialize and reset themselves. For some programs, for example, there is a header before it prints out a set of key, value pairs which you can parse by using a global flag to say if you're in the output section or not. But this flag has to be reused between every file so an error in the first can affect how the rest are parsed.

We can be backwards compatible with old-style parsers by checking the type of parser, if it's a function we proceed like before. If it's an object, we can maybe have functions/callbacks like `onInit()`, `onNewFile()`, `parseLine()`, or even on `onFailure()` so the parser can fill in blanks with default results. We can immediately put this to use with the `regex-parser` by only constructing the regexes once rather than per-line.

There would be one "breaking" change though. We probably should only pass the additional user parser parameters to `onInit()` rather than to `parseLine()` every time, but since that feature was only added yesterday, it probably won't break anything besides `regex-parser`.

**Comment by ledif** [comment]
Support added in #47.

**Comment by dlatypov** [comment]
Except for the `onFailure()` callback, this functionality was implemented in #47
